#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-travis-lint
Version  : 2.0.0
Release  : 3
URL      : https://rubygems.org/downloads/travis-lint-2.0.0.gem
Source0  : https://rubygems.org/downloads/travis-lint-2.0.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: rubygem-travis-lint-bin
BuildRequires : ruby
BuildRequires : rubygem-json
BuildRequires : rubygem-rdoc

%description
No detailed description available

%package bin
Summary: bin components for the rubygem-travis-lint package.
Group: Binaries

%description bin
bin components for the rubygem-travis-lint package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n travis-lint-2.0.0
gem spec %{SOURCE0} -l --ruby > rubygem-travis-lint.gemspec

%build
gem build rubygem-travis-lint.gemspec

%install
gem_dir=$(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .${gem_dir} \
--bindir .%{_bindir} \
travis-lint-2.0.0.gem

mkdir -p %{buildroot}${gem_dir}
cp -pa .${gem_dir}/* \
%{buildroot}${gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/travis-lint-2.0.0.gem
/usr/lib64/ruby/gems/2.2.0/doc/travis-lint-2.0.0/ri/Net/HTTP/cdesc-HTTP.ri
/usr/lib64/ruby/gems/2.2.0/doc/travis-lint-2.0.0/ri/Net/cdesc-Net.ri
/usr/lib64/ruby/gems/2.2.0/doc/travis-lint-2.0.0/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/gems/travis-lint-2.0.0/bin/travis-lint
/usr/lib64/ruby/gems/2.2.0/specifications/travis-lint-2.0.0.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/travis-lint
